### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by vweevers** [Level/levelup#456]
@ralphtheninja @juliangruber 

Following https://github.com/Level/levelup/pull/455#discussion_r135388839, here's a list of possible improvements as well as related issues. We can address these with multiple PRs or break it up into issues. I thought it best to first get an overview, and to start a discussion on the general goals:

- Consistent wording
- Reduce focus on LevelDOWN and LevelDB, make it generic
- Express a preference for using \*down layers (like `encoding-down`) to extend functionality
- Drop documentation that can be found elsewhere.
- Recommend `level`

**Notes per section**

- [Introduction](https://github.com/Level/levelup/blob/f95eaf8ed55a8c9f69db839f1993a0d612324bdc/README.md#introduction)
  - [x] Rewrite. Possibly merge with [Relationship to LevelDOWN](https://github.com/Level/levelup/blob/f95eaf8ed55a8c9f69db839f1993a0d612324bdc/README.md#relationship-to-leveldown). Sentences like "LevelDOWN is now optional because LevelUP can be used with alternative backends" are not wrong but I'd prefer opening with "LevelUP can be used with multiple backends" and thén saying "most commonly that's LevelDOWN".
  - [x] Remove "LevelUP will look for LevelDOWN and throw an error if it can't find it in its Node require() path. It will also tell you if the installed version of LevelDOWN is incompatible.". No longer true.
  - [x] Level should be the preferred way of using `levelup` + `encoding-down` + `leveldown`
  - [x] I feel it's important we keep the description of characteristics (e.g. lexicographical order), but maybe it can be explained *not* through a description of `LevelDB`, but by saying "backends follow the characteristics of LevelDB: `<list of characteristics>`.
- [Tested & supported platforms](https://github.com/Level/levelup/blob/f95eaf8ed55a8c9f69db839f1993a0d612324bdc/README.md#tested--supported-platforms):
  - [x] Remove (backend-specific) list of platforms
  - [x] But perhaps do mention we support both Node.js and browser
  - [x] Improve LevelDOWN's documentation: Level/leveldown#380
- [Basic usage](https://github.com/Level/levelup/blob/f95eaf8ed55a8c9f69db839f1993a0d612324bdc/README.md#basic-usage)
  - [x] No longer true: "All operations are asynchronous although they don't necessarily require a callback if you don't need to know when the operation was performed."
- [`db.createReadStream([options])`](https://github.com/Level/levelup/blob/f95eaf8ed55a8c9f69db839f1993a0d612324bdc/README.md#dbcreatereadstreamoptions)
  - [x] Drop this sentence: "The standard pause(), resume() and destroy() methods are implemented on the ReadStream, as is pipe() (see below). 'data', 'error', 'end' and 'close' events are emitted." Linking to Node.js documentation should suffice.
- [Extending LevelUP](https://github.com/Level/levelup/blob/f95eaf8ed55a8c9f69db839f1993a0d612324bdc/README.md#extending-levelup)
  - [x] "When attempting to extend the functionality of LevelUP, it is recommended that you consider using **level-hooks and/or level-sublevel**.": I would personally recommend `subleveldown` and similar \*down layers now. Alternatively we could remove this text and just link to the wiki.

**General**

- [x] Pick one of "database" / "store" / "database store" / "underlying store" / "database backend" / "LevelDB store": #502
- [x] After the introduction, generalize or remove references to LevelDB, assuming the introduction has made it clear that a "store" (or whatever word we settle on) is abstract. E.g. "opening the underlying store with LevelDB" => "opening the store".
- [x] "Node.js-style readable stream": drop the `-style` suffix? Seems to suggest it's *like* a Node.js stream, but not actually.
- [x] "records" / "entries" => "entries"
- [x] "key/value pairs" => "key-value pairs"
- [x] "data store" => "store"
- [x] LevelUP => `levelup`, LevelDOWN => `leveldown`
- [x] "can be arbitrary data objects" => "can be of any type"?
- [x] Unquote `'key'`, `'value'`, `'gte'`, etc
- [x] Add minimum Node.js version (https://github.com/Level/levelup/pull/469)
- [x] ~~Better explain encodings~~ Moved to Level/encoding-down#15
- [x] Link to a changelog: #444

**Comment by ralphtheninja** [comment]
Very good summary!

**Comment by ralphtheninja** [comment]
+1 for recommending `subleveldown`

**Comment by ralphtheninja** [comment]
@vweevers I'll add some stuff here and maybe you can update the issue as you see fit?

Remove "LevelUP will look for LevelDOWN and throw an error if it can't find it in its Node `require()` path. It will also tell you if the installed version of LevelDOWN is incompatible.". No longer true.

**Comment by ralphtheninja** [comment]
"**The [level](https://github.com/level/level) package is available as an alternative installation mechanism.** Install it instead to automatically get both LevelUP & LevelDOWN. It exposes LevelUP on its export (i.e. you can `var leveldb = require('level')`)."

`level` should be the preferred way of using levelup + encoding-down + leveldown

**Comment by vweevers** [comment]
Should the readme stylize `encoding-down` as EncodingDOWN, in line with others?

**Comment by ralphtheninja** [comment]
> Should the readme stylize encoding-down as EncodingDOWN, in line with others?

Hmm good Q. I actually think we should change all `Xyz{UP,DOWN}` to `xyz{up,down}` everywhere, e.g. `levelup` and `leveldown` etc but not sure what others think.

**Comment by vweevers** [comment]
That's generally my preference too; the package name is the canonical name.

**Comment by ralphtheninja** [comment]
> typing DOWN is a pita too

LOL

**Comment by ralphtheninja** [comment]
Polling tiiiime! :man_dancing: 

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRTV21RF1VP85SK3H8GFGHYN/database)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRTV21RF1VP85SK3H8GFGHYN/database/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRTV21RF1VP85SK3H8GFGHYN/store)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRTV21RF1VP85SK3H8GFGHYN/store/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRTV21RF1VP85SK3H8GFGHYN/database%20store)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRTV21RF1VP85SK3H8GFGHYN/database%20store/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRTV21RF1VP85SK3H8GFGHYN/underlying%20store)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRTV21RF1VP85SK3H8GFGHYN/underlying%20store/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRTV21RF1VP85SK3H8GFGHYN/database%20backend)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRTV21RF1VP85SK3H8GFGHYN/database%20backend/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRTV21RF1VP85SK3H8GFGHYN/LevelDB%20store)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BRTV21RF1VP85SK3H8GFGHYN/LevelDB%20store/vote)

**Comment by vweevers** [comment]
The way I see it, combining *down layers (and other modules) can give you a full-featured *database*. On top of a simple (yet powerful) key-value *store*. Calling that store *underlying* is optional but helps when you view levelup itself as a store.

**Comment by vweevers** [comment]
Added to the list above:

- "records" / "entries" => "entries"
- "key/value pairs" => "key-value pairs"
- "data store" => "store"
- "can be arbitrary data objects" => "can be of any type"?

**Comment by vweevers** [comment]
@ralphtheninja @juliangruber how do you feel about unquoting `'key'`, `'value'`, `'gte'`, etc? Make it easier to read. At least all the things that are properties of an object, where we don't need to explain that they're strings. E.g. `key`, `value`, `gte`.

**Comment by ralphtheninja** [comment]
Maybe we could move the points on encodings, explaining `encoding-down` etc to `level` repo?

**Comment by vweevers** [comment]
> Maybe we could move the points on encodings, explaining encoding-down etc to the level repo? 

I was thinking we explain encodings in `encoding-down`, and link to it from both `levelup` and `level`. Until more people know to prefer `level` over `levelup`, I don't think we should remove documentation from `levelup`. Or even at all, because there will always be an audience for `levelup`.

**Comment by vweevers** [comment]
(i.e. I mean to open an issue in `encoding-down`)

**Comment by vweevers** [comment]
Removed from the above list:

- Explain encodings: moved to Level/encoding-down#15
- Update abstract-leveldown example in readme: to do *after* v2, and we already have #449 for this
- Describe responsibilities of levelup vs \*down: not explicitly explained but I think at least the relation is clearer now.

With that, this is done.
