### ISSUE TITLE
put back support for node 4

### ISSUE THREAD

**Issue by ralphtheninja** [Level/levelup#516]
Apparently many are still using node 4 and it's a shame they can't use levelup. I was thinking about this today and iirc it's not about promises at all, but rather the `[ promise, callback ] = promisify()` destructuring that's the problem and it should be easy for us to release a patch, also completely internal logic so no api changes are required.

`promisify()` might as well just return an object literal and we should be good to go.

- [x] fix destructuring
- [x] put node 4 back in `deferred-leveldown`: Level/deferred-leveldown#31
- [x] add badge to `encoding-down`: Level/encoding-down#25
- [x] restore 4 in `level-packager`: Level/packager#40 (pending levelup update)
- [x] restore 4 in `level`: Level/level#67 (pending levelup update)

**Comment by vweevers** [comment]
SGTM. And for the strategy (#470), we can simply say we support all versions until end of life. This'd mean we support node 4 until april 2018.

**Comment by vweevers** [comment]
Done 🎈
